# Generated by Django 6.1 on 2026-08-19 08:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='creator_visitor_id',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
        migrations.AddField(
            model_name='participant',
            name='visitor_id',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
    ]
